scan_filter_chain:
- name: scan_angle_filter
  type: vizzy_sensors/ScanAngleFilter
  params:
    min_angle: -1.1
    max_angle: 1.1
- name: nan_to_inf_filter
  type: vizzy_sensors/NanToInfFilter
- name: footprint_filter
  type: vizzy_sensors/VizzyFootprintFilter
  params:
    footprint_frame: base_footprint
    footprint: [0.1,0.1,0.1,-0.1,-0.3,-0.1,-0.3,0.1]

