hokuyo_laser_filters:
  ros__parameters:
    scan_filter_chain:
      - name: scan_angle_filter
        type: vizzy_sensors/ScanAngleFilter
      - name: nan_to_inf_filter
        type: vizzy_sensors/NanToInfFilter
      - name: footprint_filter
        type: vizzy_sensors/VizzyFootprintFilter
    min_angle: -1.1
    max_angle: 1.1
    footprint_frame: "base_footprint"
    footprint: [0.1, 0.1, 0.1, -0.1, -0.3, -0.1, -0.3, 0.1]

hokuyo_laser_filters_rear:
  ros__parameters:
    scan_filter_chain:
      - name: scan_angle_filter
        type: vizzy_sensors/ScanAngleFilter
      - name: nan_to_inf_filter
        type: vizzy_sensors/NanToInfFilter
      - name: footprint_filter
        type: vizzy_sensors/VizzyFootprintFilter
    min_angle: -1.1
    max_angle: 1.1
    footprint_frame: "base_footprint"
    footprint: [0.1, 0.1, 0.1, -0.1, -0.3, -0.1, -0.3, 0.1]